Define `cfg(hawk)` during analysis
Summary
--

I ran into this when vendoring `unicode_names2` in Ruff (astral-sh/ruff#28784) because it has some
nightly-only test features. For Clippy, I was able to use:

```rust
 #![cfg_attr(all(test, not(clippy)), feature(test))]
```

but `not(hawk)` wasn't available. This PR adds `--cfg=hawk` to several rust invocations to enable
this usage.

Test Plan
--

A couple of new tests to exercise the feature and manual testing on my Ruff branch:

```console
❯ cargo build --bins
❯ cargo +1.98.1 run --bin cargo-hawk -- check \
  --manifest-path ../ruff/Cargo.toml \
  --target-dir /Users/brw/astral/ruff/target/hawk \
  -D warnings
... 6 actual errors but hawk runs successfully
```

vs the published version:

```console
❯ cargo +1.98.1 hawk check --target-dir target/hawk -D warnings
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> crates/ruff_unicode_names2/src/lib.rs:71:48
   |
71 | #![cfg_attr(all(test, not(clippy), not(hawk)), feature(test))]
   |                                                ^^^^^^^^^^^^^
```